name: Algolia # Reindex site search on Algolia

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  reindex:
    runs-on: ubuntu-latest
    steps:
      - name: Reindex Algolia
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               --user ${{ secrets.CRAWLER_USER_ID }}:${{ secrets.CRAWLER_API_KEY }} \
               "https://crawler.algolia.com/api/1/crawlers/${{ secrets.CRAWLER_ID }}/reindex"
